version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8001
    environment:
      - PYTHONUNBUFFERED=1
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test@123"
      
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
